name: Github Pages

on:
  push:
    branches:
      - master  # Source code branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Specify the Ruby version

      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: jeffreytse/jekyll-deploy-action@v0.5.1
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: 'in27sung/blog'
          branch: 'gh-pages'
          jekyll_src: './'
          jekyll_cfg: '_config.yml'
          jekyll_baseurl: '/jekyll-theme-yat'
          cname: ''
          actor: ''
